### ISSUE TITLE
Date Error on attendance page

### ISSUE THREAD

**Issue by caricchow** [attendanceproject/djattendance#506] opened 2017-06-10 21:32 UTC
- [x] I put in a leave slip for Tue 6/6 and on the summary section above the calendar view on the attendance page it says 6/5. Time zone issue...? idk 0679937
- [x] Also, on some computers the TAs show up as [Object] object

**Comment by billyeh** [comment] 2017-06-10 21:34
Also, on some computers the TAs show up as `[Object] object`

**Comment by billyeh** [comment] 2017-06-19 22:33
Closing since we can't reproduce the second error.

**Closed by billyeh** 2017-06-19 22:33 UTC
Labels: bug
