### ISSUE TITLE
Bug Fix Request 09/09/18

### ISSUE THREAD

**Issue by AngeloBelUCSD** [attendanceproject/djattendance#1402] opened 2018-09-15 23:01 UTC
By Austin Anderson

Non Critical Bug
Description
Designated hours task performed box. Max # of characters allowed in field is 141, throws error indicating a 140 max char limit. Likely an off-by-one-error

**Comment by davidhtien** [comment] 2018-09-26 00:38
May or may not be related to a bug on life-studies, @kcmin reported that you need 251 words to submit a LS

**Comment by joysyu** [comment] 2018-11-18 00:02
I think this has been fixed! I cannot reproduce it and there's a 140 max char limit.

**Comment by finben** [comment] 2018-12-20 01:10
Let's close it out. Fixed

**Closed by finben** 2018-12-20 01:10 UTC
