### ISSUE TITLE
python-coveralls install broken on windows

### ISSUE THREAD

**Issue by haileyl** [attendanceproject/djattendance#143] opened 2015-06-24 20:34 UTC
Hitting this issue with sh/pbs when installing django 1.8 on windows.
https://github.com/z4r/python-coveralls/issues/26

**Comment by ricefield** [comment] 2015-06-24 21:03
@lifeunion should we remove the coveralls dependency? This isn't exactly crucial at the moment, we can add it back in when the issue is fixed, or find an alternative when we need it

**Comment by billyeh** [comment] 2017-06-06 23:07
Closing because the Windows issue is solved in that repo.

**Closed by billyeh** 2017-06-06 23:07 UTC
