### ISSUE TITLE
Reconsider Room Reservation for UI/UX

### ISSUE THREAD

**Issue by yipingbenjaminliu** [attendanceproject/djattendance#746] opened 2018-02-20 21:34 UTC

**Comment by ruthnan** [comment] 2018-03-12 07:36
Wait for my commit @joeyu23

**Comment by finben** [comment] 2018-05-15 03:26
@caricchow @xuefeizheng I don't see that we have a design document for this. Maybe the design team can come up with one for room reservation page?

**Comment by JoannaRumbley** [comment] 2018-05-16 22:44
See #1151 
@isaactsou is working on it. Closing this one since it's a duplicate of #1151

**Comment by JoannaRumbley** [comment] 2018-05-16 22:46
Actually...let's keep this one open since it's already assigned to ppl. :)
When it's done, please check it off on 1151. Thx

**Comment by iamsitting** [comment] 2018-06-17 01:41
Let's close this. The designers are assigned in #1151

**Closed by iamsitting** 2018-06-17 01:41 UTC
